global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-service'  # FastAPI
    static_configs:
      - targets: ['fastapi-server:8000']

  - job_name: 'postgresql-db'  # PostgreSQL
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis-service'  # Redis
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'  # RabbitMQ
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
