global:
  scrape_interval: 15s  # 메트릭 수집 인터벌
  evaluation_interval: 15s  # 메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus'  # Prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-service'  # FastAPI
    static_configs:
      - targets: ['fastapi-server:8000']

  - job_name: 'postgres-exporter'  # PostgreSQL Exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

#  - job_name: 'redis'  # Redis 서비스
#    static_configs:
#      - targets: ['redis:6379']

  - job_name: 'redis-exporter'  # Redis Exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq-exporter'  # RabbitMQ Exporter
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'cadvisor'  # cAdvisor
    static_configs:
      - targets: ['cadvisor:8080']
